### ISSUE TITLE
Support for other countries?

### ISSUE THREAD

**Issue by civarson** [amaximus/pollen_hu#1]
Hi, I've been looking for something like this forever but I live in Texas in the US. Would you be able to pull global data from pollen.com?

**Comment by civarson** [comment]
Realizing pollen.com might be for US only. For example you could scrape a page by zipcode:
https://www.pollen.com/forecast/current/pollen/78701

**Comment by amaximus** [comment]
This custom integration gets its data from the Hungarian National Public Health Office in its proprietary format; it has no API, thus a HTML page had to be scraped. Due to this proprietary solution there are no plans extending it.

Having a quick look on pollen.com, https://www.pollen.com/forecast/current/pollen/<zipcode> doesn't use static page elements, therefore the scrape might not work (the pollen data is generated by some Javascript scripts).
